### ISSUE TITLE
Prof. Anderson's Evaluation

### ISSUE THREAD

**Issue by kenbod** [alne4294/TheTeam_Queue#12]
Great work on the Homework assignment; easy to understand code and a nice application domain to target. I liked learning more about Flask and I liked the use of sqlite for the database. I also enjoyed the enthusiastic commit messages. Good job!

**Comment by justinmcbride** [comment]
Just to clarify, the commits from LoganBates are actually from Tyler Bussell. He was just using Logan's computer, and git used Logan's information to sign the commits.
